# Generated by Django 4.2.20 on 2026-08-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='users.project'),
        ),
        migrations.AddIndex(
            model_name='routetarget',
            index=models.Index(fields=['route', 'is_active'], name='routes_rout_route_i_e6756e_idx'),
        ),
        migrations.AddIndex(
            model_name='routetarget',
            index=models.Index(fields=['url'], name='routes_rout_url_1959b4_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['project', 'method', 'path'], name='routes_rout_project_68cb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['method', 'path'], name='routes_rout_method_8dac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='routes_rout_is_acti_d0dc30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('project', 'method', 'path')},
        ),
    ]
