# Generated by Django 4.2.20 on 2026-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cache_ttl_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='downstream_service',
            field=models.CharField(choices=[('user-service', 'User Service'), ('product-service', 'Product Service'), ('order-service', 'Order Service')], default='product-service', max_length=80),
        ),
    ]
