# Generated by Django 4.2.20 on 2026-08-22 15:44

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def copy_downstream_services(apps, schema_editor):
    BackendService = apps.get_model('routes', 'BackendService')
    Route = apps.get_model('routes', 'Route')
    for route in Route.objects.all():
        service_slug = route.downstream_service or 'backend-service'
        service_name = service_slug.replace('-', ' ').title()
        service, _ = BackendService.objects.get_or_create(
            project_id=route.project_id,
            slug=slugify(service_slug) or 'backend-service',
            defaults={'name': service_name},
        )
        route.backend_service_id = service.id
        route.save(update_fields=['backend_service'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('routes', '0003_route_cache_ttl_seconds_route_downstream_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='backendservice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_services', to='users.project'),
        ),
        migrations.AddField(
            model_name='route',
            name='backend_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.backendservice'),
        ),
        migrations.RunPython(copy_downstream_services, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='route',
            name='downstream_service',
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['backend_service', 'method'], name='routes_rout_backend_373903_idx'),
        ),
        migrations.AddIndex(
            model_name='backendservice',
            index=models.Index(fields=['project', 'is_active'], name='routes_back_project_ec838c_idx'),
        ),
        migrations.AddIndex(
            model_name='backendservice',
            index=models.Index(fields=['slug'], name='routes_back_slug_29bfa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backendservice',
            unique_together={('project', 'slug')},
        ),
    ]
