# Generated by Django 4.2.20 on 2026-08-22 19:55

from django.db import migrations, models


def copy_first_target_url(apps, schema_editor):
    Route = apps.get_model('routes', 'Route')
    RouteTarget = apps.get_model('routes', 'RouteTarget')
    for route in Route.objects.all():
        target = RouteTarget.objects.filter(route_id=route.id, is_active=True).order_by('id').first()
        if target is None:
            target = RouteTarget.objects.filter(route_id=route.id).order_by('id').first()
        if target is not None:
            route.target_url = target.url
            route.save(update_fields=['target_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_backendservice_remove_route_downstream_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='load_balancing',
        ),
        migrations.AddField(
            model_name='route',
            name='target_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(copy_first_target_url, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='RouteTarget',
        ),
    ]
