# Generated by Django 4.2.20 on 2026-08-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_route_load_balancing_route_target_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='cache_ttl_seconds',
        ),
    ]
