# Generated by Django 4.2.20 on 2026-08-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='window_seconds',
        ),
    ]
