# Generated by Django 4.2.20 on 2026-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_project_rate_limit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='users_proje_owner_i_4385fa_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plan',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='users_proje_owner_i_6f13b7_idx'),
        ),
    ]
