# Generated by Django 4.2.20 on 2026-08-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('analytics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='users.project'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='routes.route'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['project', 'created_at'], name='analytics_r_project_e2a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code', 'created_at'], name='analytics_r_status__44cae6_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['endpoint', 'created_at'], name='analytics_r_endpoin_bea02f_idx'),
        ),
    ]
