# Generated by Django 4.2.20 on 2026-08-22 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_application_routepermission_and_more'),
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='authentication.application'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='downstream_service',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['application', 'created_at'], name='analytics_r_applica_ed6ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['downstream_service', 'created_at'], name='analytics_r_downstr_55a622_idx'),
        ),
    ]
