# Generated by Django 4.2.20 on 2026-08-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.project'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['project', 'revoked_at', 'expires_at'], name='authenticat_project_056759_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['prefix'], name='authenticat_prefix_7e7b84_idx'),
        ),
    ]
