# Generated by Django 4.2.20 on 2026-08-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('routes', '0003_route_cache_ttl_seconds_route_downstream_service'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('window_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='routepermission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authentication.application'),
        ),
        migrations.AddField(
            model_name='routepermission',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_permissions', to='routes.route'),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.project'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='authentication.application'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['application', 'revoked_at', 'expires_at'], name='authenticat_applica_8364df_idx'),
        ),
        migrations.AddIndex(
            model_name='routepermission',
            index=models.Index(fields=['application', 'is_active'], name='authenticat_applica_173b45_idx'),
        ),
        migrations.AddIndex(
            model_name='routepermission',
            index=models.Index(fields=['route', 'is_active'], name='authenticat_route_i_53ca9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routepermission',
            unique_together={('application', 'route')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['project', 'is_active'], name='authenticat_project_39b0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['slug'], name='authenticat_slug_b9fe14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('project', 'slug')},
        ),
    ]
