# Generated by Django 4.2.20 on 2026-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_application_routepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
