# Generated by Django 4.2.20 on 2026-08-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_application_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plan',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], default='normal', max_length=20),
        ),
    ]
