# Generated by Django 4.2.20 on 2026-08-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_application_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='application',
            name='window_seconds',
        ),
    ]
