# Generated by Django 4.2.20 on 2026-08-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_application_rate_limit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='authenticat_prefix_7e7b84_idx',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='prefix',
        ),
    ]
